# -*- coding: utf-8 -*-
"""myfirstapp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IT9n8oj2mJUum5af4_60rLrunsbbi1w4
"""

from dash import Dash, html

app = Dash(__name__)

app.layout = html.Div("Hello, Railway!")

if __name__ == "__main__":
    app.run_server(host="0.0.0.0", port=8050)